- name: ControlPlane Setup
  hosts: localhost
  connection: local
  become: yes
  vars:
    os: "xUbuntu_22.04"
    crio_version: "1.30.4"
    kubernetes_version: "v1.30"

  tasks:
    - name: CommonTask
      import_tasks: common_tasks.yaml