apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alertmanager
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-server
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
