apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
spec:
  rules:
  - host: grafana.test.local
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 80